services:
  db:
    image: postgres:16
    container_name: municipal_db
    environment:
      POSTGRES_DB: municipal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - municipal_pg_data:/var/lib/postgresql/data

volumes:
  municipal_pg_data:
